spring:
  application:
    name: pumer
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  mvc:
    view:
      404:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0
  session:
    store-type: redis
datasource:
   druid:
      url: jdbc:mysql://qdm114116425.my3w.com:3306/qdm114116425_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
      username: qdm114116425
      password: wangzhen
      filters: stat,slf4j
      initialSize: 5
      maxActive: 100
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wz.pumer.beans
  check-config-location: true

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mapper:
    mappers:
        - com.wz.pumer.utils.MyMapper
    not-empty: false
    identity: MYSQL